#!/bin/bash
# ============================================================================
#  HIBP Jenkins Deployment Wrapper
#  Non-interactive wrapper for hibp_deploy.sh — used by Jenkinsfile
#  Accepts ENV vars for configuration instead of interactive wizard
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HIBP_SCRIPT="$SCRIPT_DIR/hibp_deploy.sh"
LOG_FILE="/tmp/hibp_jenkins_deploy.log"

# Terminal colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

# Logging
log()     { echo -e "${CYAN}[$(date +%H:%M:%S)]${NC} $1" | tee -a "$LOG_FILE"; }
success() { echo -e "${GREEN}✓${NC} $1" | tee -a "$LOG_FILE"; }
error()   { echo -e "${RED}✗ ERROR:${NC} $1" | tee -a "$LOG_FILE"; exit 1; }
warn()    { echo -e "${YELLOW}⚠${NC} $1" | tee -a "$LOG_FILE"; }

# ── Configuration from ENV or defaults ──────────────────────────────────────
HIBP_DIR="${HIBP_DATA_DIR:-/apps/hibp/hibp-data}"
SERVICE_DIR="${HIBP_SERVICE_DIR:-/apps/hibp/hibp-service}"
PORT="${HIBP_PORT:-3001}"
SERVICE_USER="${HIBP_SERVICE_USER:-hibpuser}"
DOTNET_DIR="${HIBP_DOTNET_DIR:-/apps/hibp/dotnet9}"
PINGONE_IPS="${HIBP_PINGONE_IPS:-}"
ADMIN_IP="${HIBP_ADMIN_IP:-}"
SKIP_DOWNLOAD="${HIBP_SKIP_DOWNLOAD:-false}"
SKIP_INDEX="${HIBP_SKIP_INDEX:-false}"

# Jenkins-specific: disable interactive prompts
export HIBP_JENKINS_MODE=true

header() {
    echo ""
    echo -e "${BOLD}${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    printf "${BOLD}${BLUE}║  %-58s║${NC}\n" "$1"
    echo -e "${BOLD}${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

# ── Validate prerequisites ──────────────────────────────────────────────────
validate_env() {
    header "Validating Jenkins Environment"

    log "Configuration:"
    printf "  %-25s %s\n" "HIBP_DATA_DIR:" "$HIBP_DIR"
    printf "  %-25s %s\n" "HIBP_SERVICE_DIR:" "$SERVICE_DIR"
    printf "  %-25s %s\n" "HIBP_PORT:" "$PORT"
    printf "  %-25s %s\n" "HIBP_SERVICE_USER:" "$SERVICE_USER"
    printf "  %-25s %s\n" "HIBP_DOTNET_DIR:" "$DOTNET_DIR"
    printf "  %-25s %s\n" "HIBP_PINGONE_IPS:" "${PINGONE_IPS:-none}"
    printf "  %-25s %s\n" "HIBP_ADMIN_IP:" "${ADMIN_IP:-none}"
    printf "  %-25s %s\n" "HIBP_SKIP_DOWNLOAD:" "$SKIP_DOWNLOAD"
    printf "  %-25s %s\n" "HIBP_SKIP_INDEX:" "$SKIP_INDEX"
    echo ""

    # Check sudoers
    if ! sudo -n true 2>/dev/null; then
        error "Jenkins user needs passwordless sudo. Add to sudoers file."
    fi
    success "Passwordless sudo available"

    # Check disk space
    local avail=$(df -BG "$HIBP_DIR" 2>/dev/null | awk 'NR==2{print $4}' | tr -d 'G' || echo 0)
    if [ "${avail:-0}" -lt 100 ] 2>/dev/null; then
        warn "Only ${avail}GB free — download will fail if you have less than 100GB"
    else
        success "Disk space: ${avail}GB available"
    fi
}

# ── Create config file for hibp_deploy.sh ──────────────────────────────────
create_config() {
    header "Creating HIBP Configuration"

    local config_file="$SCRIPT_DIR/hibp_deploy.config"

    log "Writing config to: $config_file"

    cat > "$config_file" << EOF
# HIBP Deploy Configuration — auto-generated by Jenkins
# Generated: $(date)

HIBP_DIR="$HIBP_DIR"
SERVICE_DIR="$SERVICE_DIR"
PORT="$PORT"
PARALLELISM="${HIBP_PARALLELISM:-16}"
SERVICE_USER="$SERVICE_USER"
DOTNET_DIR="$DOTNET_DIR"
PINGONE_IPS="$PINGONE_IPS"
ADMIN_IP="$ADMIN_IP"
NODE_BIN="$(command -v node 2>/dev/null || echo '')"
PYTHON_BIN="$(command -v python3 2>/dev/null || echo '/usr/bin/python3')"
EOF

    success "Config created: $config_file"
}

# ── Run individual deployment stages ───────────────────────────────────────
run_stage() {
    local stage="$1"
    local description="$2"

    header "$description"

    # Check if script exists
    [ ! -f "$HIBP_SCRIPT" ] && error "hibp_deploy.sh not found at $HIBP_SCRIPT"

    log "Running: $stage"
    if bash "$HIBP_SCRIPT" "$stage" 2>&1 | tee -a "$LOG_FILE"; then
        success "$description completed"
        return 0
    else
        error "$description failed"
        return 1
    fi
}

# ── Main deployment flow ────────────────────────────────────────────────────
main() {
    header "HIBP Jenkins Deployment"

    log "Start time: $(date)"
    log "Jenkins build: ${BUILD_ID:-unknown}"
    log "Jenkins workspace: ${WORKSPACE:-$(pwd)}"
    echo ""

    # 1. Validate environment
    validate_env

    # 2. Create config
    create_config

    # 3. Run prerequisite check
    run_stage "prereqs" "Step 0 — Prerequisites Check"

    # 4. Create hibpuser if needed
    run_stage "create-user" "Step 0b — Create Service User"

    # 5. Create directories
    run_stage "download" "Step 1 — Create Directories" || true

    # 6. Create weak word list (always runs)
    log "Step 2 — Create Weak Password List"
    if [ ! -f "$HIBP_DIR/weak_passwords.txt" ]; then
        run_stage "download" "Creating weak password list"
    else
        success "Weak password list already exists: $HIBP_DIR/weak_passwords.txt"
    fi

    # 7. Handle HIBP download (optional, skippable)
    if [ "$SKIP_DOWNLOAD" = "true" ]; then
        warn "Skipping HIBP download (HIBP_SKIP_DOWNLOAD=true)"
        warn "Note: Download takes 4-8 hours. You can run later:"
        warn "  ./hibp_deploy.sh download"
    else
        if [ ! -f "$HIBP_DIR/pwnedpasswords.txt" ]; then
            warn "Hash file not found. Download will take 4-8 hours."
            warn "To skip: set HIBP_SKIP_DOWNLOAD=true"
            run_stage "download" "Step 3 — Download HIBP Hash File" || {
                warn "Download failed or timed out"
                warn "This is expected in Jenkins (long-running job)"
                warn "Run manually on EC2: ./hibp_deploy.sh download"
            }
        else
            success "Hash file already exists: $HIBP_DIR/pwnedpasswords.txt"
        fi
    fi

    # 8. Handle index build (optional, skippable)
    if [ "$SKIP_INDEX" = "true" ]; then
        warn "Skipping index build (HIBP_SKIP_INDEX=true)"
        warn "Note: Build takes 30-90 minutes. You can run later:"
        warn "  ./hibp_deploy.sh build-index"
    else
        if [ ! -f "$HIBP_DIR/pwnedpasswords.idx" ]; then
            if [ -f "$HIBP_DIR/pwnedpasswords.txt" ]; then
                warn "Index not found. Build will take 30-90 minutes."
                warn "To skip: set HIBP_SKIP_INDEX=true"
                run_stage "build-index" "Step 4 — Build Binary Search Index" || {
                    warn "Index build failed or timed out"
                    warn "This is expected in Jenkins (long-running job)"
                    warn "Run manually on EC2: ./hibp_deploy.sh build-index"
                }
            else
                warn "Hash file not found — skipping index build"
                warn "Run download first: ./hibp_deploy.sh download"
            fi
        else
            success "Index already exists: $HIBP_DIR/pwnedpasswords.idx"
        fi
    fi

    # 9. Install server, nginx, firewall, systemd
    run_stage "install" "Step 5 — Install Server, nginx, Firewall, Systemd"

    # 10. Start services
    run_stage "start" "Step 6 — Start Services"

    # 11. Run tests
    run_stage "test" "Step 7 — Run Tests"

    echo ""
    header "Deployment Complete"
    success "HIBP service deployed successfully"
    log "End time: $(date)"
    log "Full log: $LOG_FILE"
    echo ""

    return 0
}

# ── Run main ────────────────────────────────────────────────────────────────
main "$@"
